### ISSUE TITLE
Allow override of Java options without overriding the entrypoint

### ISSUE THREAD

**Issue by adriancole** [hypertrace/hypertrace-gradle-docker-plugins#17]
Right now, what would be done in JAVA_OPTS are generated at build time and inlined into the entrypoint. This makes it difficult to add settings such as overriding heap, changing logging config, turning on and off verbose:gc etc without also having to recreate the entrypoint.

For example, this attempt would have undone any options setup in the gradle plugin
https://github.com/hypertrace/hypertrace/blob/68bfd41cad4515e0e8c18c0693cf03423d031224/docker/scripts/start-platform.sh

I believe the simplest way is to add JAVA_OPTS as is typically used for this instead of trying to up-front engineer a list of variables to do things similarly, as for example schema-registry does and has a different one for heap vs gc vs logging config etc. The rationale is that there's heavy cost of re-deploying this plugin across N repos and also the impact is only ourselves. JAVA_OPTS is commonly used and well understood enough including its cons to allow a way to progress with a lot of thrashing, discussion or rebuild/deploy based iterations.

Note: JAVA_TOOL_OPTIONS exists, but it is not a good choice for this, as it was designed to push down agent config https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#tooloptions

IOTW, this property would change this also https://github.com/hypertrace/attribute-service/blob/a0439235410d5c2b921715201ba06bfe946e979a/helm/templates/deployment.yaml#L64-L65

**Comment by aaron-steinfeld** [comment]
Agree this is a good thing to have and looked at it briefly. It'll be a bit more involved to implement because the current implementation that our plugin is built on allows adding jvm opts at build time, but they get inlined as literals. it makes more sense to add JAVA_OPTS the env variable to allow overrides at runtime. To get that in, we'll need to customize the entry point internally, which means likely changing the whole implementation of docker file generation to fully own it. At that point we can
also introduce a start script as we discussed elsewhere, so while a bit of effort would unlock several improvements and allow cleaning up of some tech debt.

If not pressing, I can probably use this as a good self-contained project when flying on monday.

**Comment by adriancole** [comment]
there are still many projects to update, and ones that would change wrt docker monday are maybe 2, and maybe would need change also weds :P thanks for taking this on.
